services:
  runner:
    image: docker.io/library/runner-image:latest
    restart: always
    environment:
      - REPO=<user>/<repo>
      - TOKEN=<your personnal access token>
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.35'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M